# Page settings

baseURL = "https://opencloudday.com/"
languageCode = "es-mx"
defaultContentLanguage = "es"
title = "Open Cloud Day México"
theme = "opencloudday"
googleAnalytics = "UA-21077034-38"
publishDir = "docs"

[params]
    author = "Software Guru"
    description = "Open Cloud Day es una conferencia gratuita presentada por Microsoft y Red Hat enfocadas en desarrollo de aplicaciones y gestión de infraestructura cloud."

    [params.navbar]
        name = "Open Cloud Day México"
        url = "/"

        [[params.navbar.nav]]
        name = "Agenda"
        url = "/agenda"

        [[params.navbar.nav]]
        name = "Registro"
        url = "/registro"
        button = true


    [params.header]
        name = "Open Cloud Day México"
        tagline = "Conferencia gratuita presentada por Microsoft y Red Hat enfocada en desarrollo de aplicaciones y gestión de infraestructura de cómputo en nube híbrida."
        meta = "10 de diciembre de 2019, Ciudad de México."

    [params.summary]
        description = """Open Cloud Day es un día de conferencias técnicas gratuitas presentado por Microsoft y Red Hat con el objetivo de avanzar el conocimiento de las prácticas y tecnologías para construir aplicaciones e infraestructura en la nube con alto desempeño e interoperabilidad.

##### Dirigido a 
Desarrolladores de aplicaciones web y móviles, arquitectos de software, CTOs, ingenieros de datos.

##### Temas
Esta edición del Open Cloud Day estará principalmente enfocada en cómo y por qué utilizar software de Red Hat en Azure.

* Introducción a OpenShift.
* Laboratorios prácticos para desplegar aplicaciones en Azure Red Hat OpenShift.
* Gestión de autenticación y autorización.
* Migración de bases de datos a la nube.

"""

        [params.summary.venue]
        name = "Hotel Marriott Reforma Ciudad de México"
        address1 = "Paseo de la Reforma #276"
        address2 = "Col. Juárez. Ciudad de México"
        map = "https://binged.it/2OIhUH8"


    [params.sponsors]
      enable = true

    [params.sponsors1_list]
      enable = true
      title = "Presentado por"

      [[params.sponsors1]]
        logo = "logo-microsoft.png"
        link = "https://microsoft.com"

      [[params.sponsors1]]
        logo = "logo-redhat.png"
        link = "https://redhat.com"

    [params.sponsors2_list]
      enable = true
      title = "Organizado por"

      [[params.sponsors2]]
        logo = "sg.png"
        link = "https://sg.com.mx"

  [params.team]
    enable = true
    center = true
    title = "Conferencistas"

    # Las fotos de los mentores se almacenan en 'static/img/team'.
    # Tratar de utilizar imágenes de por lo menos 360px*360px.

    [[params.team.members]]
      img = "rolando.jpg"
      name = "Rolando Cedillo"
      position = "Director para audiencia técnica @ Microsoft"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/rolman/"]
      ]

    [[params.team.members]]
      img = "cristiam.jpg"
      name = "Cristiam Espinoza"
      position = "Principal consultant @ Microsoft"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/cristiam-espinoza-malpartida-8815763/"]
      ]

    [[params.team.members]]
      img = "david.jpg"
      name = "David Gamboa"
      position = "Solution Architect @ Red Hat"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/jose-david-gamboa-gomezflores-8622523a/"]
      ]

#    [[params.team.members]]
#      img = "rogelio.jpg"
#      name = "Rogelio Oliva"
#      position = "Azure / Cloud Native Global Black Belt @ Microsoft"
#      social = [
#        ["fa-linkedin", "https://www.linkedin.com/in/rogelio-oliva-opensource/"]
#      ]


    [params.footer]
        credit = "Open Cloud Day es otro fantástico evento de <a class='text-white' href='https://sg.com.mx' target='_blank'>Software Guru</a>"
        copyright = "Your Website"

